# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git status
    - run: git branch
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Build Application
      run: npm ci
    - name: Run Tests
      run: npm test
    - name: Report Code Coverage for Pull Request
      uses: ArtiomTr/jest-coverage-report-action@v2.0.5
      with:
        skip-step: all
        test-script: npm test
        coverage-file: ./.coverage/report.json
        base-coverage-file: ./.coverage/report.json
        github-token: ${{ secrets.SECRET_TOKEN }}
      if: github.event_name == 'pull_request'
    - run: npm run build --if-present
